path: datasets/mask  # dataset root dir
train: train/images  # train images
val: valid/images  # val images
test:  # test images

# Classes
nc: 2  # number of classes
names: ['with_mask', 'without_mask']  # class names